apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: binding-read-write
roleRef:
  kind: Role
  name: role-read-write
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: user-admin
  namespace: default
